###########################
# NEURON ACTIVATION PATTERN
###########################

# -------- Data
# cifar10, fmnist, mnist
dataset: "fmnist"

# -------- Training
n_epochs: 200
batch_size: 128
learning_rate: 1.0e-3
weight_decay: 0.0

# -------- Model
# cnn, mlp
model: "cnn"
# MLP
n_dense_blocks: 64
n_dims_hidden: 128
# CNN
n_conv_blocks: 64
n_channels_hidden: 8
n_channels_out: 8

# -------- Dataloader
num_workers: 4

# -------- Summary
save_model_every_n_epochs: 10
save_train_stats_every_n_epochs: 1
save_test_stats_every_n_epochs: 10