###########################
# NEURON ACTIVATION PATTERN
###########################

# Experiments
task: "cnn"

# Data
dataset: "fmnist"  # cifar10, fmnist, mnist

# Training
n_epochs: 200
learning_rate: 1.0e-3
weight_decay: 0.0

# Learning rate
step_size: 100
gamma: 0.1

# Model
model_type: "cnn"   # mlp, cnn
n_dense_blocks: 32
n_dims_hidden: 128
# CNN
n_conv_blocks: 128
n_channels_hidden: 8
n_channels_out: 8

# Dataloader
batch_size: 128
num_workers: 4

# Summary
save_model_every_n_epochs: 10
save_train_stats_every_n_epochs: 1
save_test_stats_every_n_epochs: 10