###########################
# NEURON ACTIVATION PATTERN
###########################


# -------- Data
# cifar10, fmnist, mnist
dataset: "cifar10"


# -------- Training
n_epochs: 1
batch_size: 512
learning_rate: 1.0e-3
weight_decay: 0.0


# -------- Network
# cnn, mlp
network: "cnn"

# MLP
n_dense_blocks: 32
n_dims_hidden: 32

# CNN
n_conv_blocks: 64
n_channels_hidden: 8
n_channels_out: 8


# -------- Dataloader
num_workers: 4


# -------- Summary
save_model_every_n_epochs: 1
save_train_stats_every_n_epochs: 1
save_test_stats_every_n_epochs: 1
