###########################
# NEURON ACTIVATION PATTERN
###########################

# Experiments
task: "69"

# Data
dataset: "cifar10"  # cifar10, fmnist, mnist

# Training
n_epochs: 2000
learning_rate: 3.0e-4
weight_decay: 0.0

# Learning rate
step_size: 100
gamma: 0.5

# Model
n_blocks: 512
n_dims_hidden: 128

# Dataloader
batch_size: 4096
num_workers: 4

# Summary
save_model_every_n_epochs: 10
save_train_stats_every_n_epochs: 1
save_test_stats_every_n_epochs: 10